=== sauce-code/packer/src/main/resources/library.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:sc="http://www.saucecode.com/packer/xml" targetNamespace="http://www.saucecode.com/packer/xml"
	elementFormDefault="qualified">

	<xs:simpleType name="string">
		<xs:restriction base="xs:string">
			<xs:pattern value="([a-z A-Z äöü ÄÖÜ ß \- / + ()])*" />
			<xs:minLength value="1" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="shortString">
		<xs:restriction base="sc:string">
			<xs:maxLength value="40" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="longString">
		<xs:restriction base="sc:string">
			<xs:maxLength value="140" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="name">
		<xs:simpleType>
			<xs:restriction base="sc:shortString" />
		</xs:simpleType>
	</xs:element>

	<xs:element name="category">
		<xs:simpleType>
			<xs:restriction base="sc:shortString" />
		</xs:simpleType>
	</xs:element>

	<xs:element name="set">
		<xs:simpleType>
			<xs:restriction base="sc:shortString" />
		</xs:simpleType>
	</xs:element>

	<xs:element name="description">
		<xs:simpleType>
			<xs:restriction base="sc:longString" />
		</xs:simpleType>
	</xs:element>

	<xs:element name="categories">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sc:category" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueCategory">
			<xs:selector xpath="sc:category" />
			<xs:field xpath="." />
		</xs:unique>
	</xs:element>

	<xs:element name="sets">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sc:set" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueSet">
			<xs:selector xpath="sc:set" />
			<xs:field xpath="." />
		</xs:unique>
	</xs:element>

	<xs:element name="items">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sc:item" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueItemName">
			<xs:selector xpath="sc:item" />
			<xs:field xpath="sc:name" />
		</xs:unique>
	</xs:element>

	<xs:element name="item">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sc:name" />
				<xs:element ref="sc:category" />
				<xs:element ref="sc:description" minOccurs="0" />
				<xs:element ref="sc:sets" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="library">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sc:sets" />
				<xs:element ref="sc:categories" />
				<xs:element ref="sc:items" />
			</xs:sequence>
		</xs:complexType>
		<xs:key name="setKey">
			<xs:selector xpath="sc:sets/sc:set" />
			<xs:field xpath="." />
		</xs:key>
		<xs:keyref name="setKeyRef" refer="sc:setKey">
			<xs:selector xpath="sc:items/sc:item/sc:sets/sc:set" />
			<xs:field xpath="." />
		</xs:keyref>
		<xs:key name="categoryKey">
			<xs:selector xpath="sc:categories/sc:category" />
			<xs:field xpath="." />
		</xs:key>
		<xs:keyref name="categoryKeyRef" refer="sc:categoryKey">
			<xs:selector xpath="sc:items/sc:item/sc:category" />
			<xs:field xpath="." />
		</xs:keyref>
	</xs:element>

</xs:schema>

=== sauce-code/packer/src/main/resources/library.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<library xmlns="http://www.saucecode.com/packer/xml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.saucecode.com/packer/xml library.xsd">
	<sets>
		<!-- This list also defines the order of all sets -->
		<set>Urlaub</set>
		<set>Festival</set>
		<set>Camping</set>
		<set>Wintersport</set>
		<set>Wandern</set>
		<set>Strand</set>
		<set>See</set>
		<set>Freibad</set>
		<set>Hallenbad</set>
	</sets>
	<categories>
		<!-- This list also defines the order of all categories -->
		<category>Finanzen</category>
		<category>Hygiene</category>
		<category>Kleidung</category>
		<category>Papiere / Unterlagen</category>
		<category>Elektronik</category>
		<category>Campingzubehör</category>
		<category>Badeartikel</category>
		<category>Sportartikel</category>
		<category>Sonstiges</category>
	</categories>
	<items>
		<!-- This list also defines the order of all items inside their category -->
		<item>
			<name>Portemonnaie</name>
			<category>Finanzen</category>
			<sets>
				<set>Festival</set>
				<set>Urlaub</set>
			</sets>
		</item>
		<item>
			<name>Bargeld</name>
			<category>Finanzen</category>
			<sets>
				<set>Urlaub</set>
				<set>Festival</set>
			</sets>
		</item>
		<item>
			<name>EC-Karte</name>
			<category>Finanzen</category>
			<sets>
				<set>Urlaub</set>
				<set>Festival</set>
			</sets>
		</item>
		<item>
			<name>Kreditkarte</name>
			<category>Finanzen</category>
			<sets>
				<set>Urlaub</set>
			</sets>
		</item>
		<item>
			<name>Notfall-Telefonnummern der Bank</name>
			<category>Finanzen</category>
			<sets>
				<set>Urlaub</set>
			</sets>
		</item>
		<item>
			<name>Bürste / Kamm</name>
			<category>Hygiene</category>
			<sets>
				<set>Urlaub</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Deodorant</name>
			<category>Hygiene</category>
			<sets>
				<set>Urlaub</set>
				<set>Festival</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Duschgel</name>
			<category>Hygiene</category>
			<sets>
				<set>Urlaub</set>
				<set>Festival</set>
				<set>Camping</set>
				<set>Freibad</set>
				<set>Hallenbad</set>
			</sets>
		</item>
		<item>
			<name>Shampoo</name>
			<category>Hygiene</category>
			<sets>
				<set>Urlaub</set>
				<set>Festival</set>
				<set>Camping</set>
				<set>Freibad</set>
				<set>Hallenbad</set>
			</sets>
		</item>
		<item>
			<name>Handtuch</name>
			<category>Hygiene</category>
			<sets>
				<set>Urlaub</set>
				<set>Festival</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Sonnencreme</name>
			<category>Hygiene</category>
			<sets>
				<set>Urlaub</set>
				<set>Festival</set>
				<set>Camping</set>
				<set>Strand</set>
				<set>See</set>
				<set>Freibad</set>
				<set>Wintersport</set>
			</sets>
		</item>
		<item>
			<name>Kontaktlinsen / Brille</name>
			<category>Hygiene</category>
			<sets>
				<set>Urlaub</set>
				<set>Festival</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Nagelpflegeset</name>
			<category>Hygiene</category>
			<sets>
				<set>Urlaub</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Rasierer</name>
			<category>Hygiene</category>
			<sets>
				<set>Urlaub</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Verhütungsmittel / Kondome</name>
			<category>Hygiene</category>
			<sets>
				<set>Urlaub</set>
				<set>Festival</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Zahnbürste + Zahnpasta</name>
			<category>Hygiene</category>
			<sets>
				<set>Urlaub</set>
				<set>Festival</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Pullover</name>
			<category>Kleidung</category>
			<sets>
				<set>Urlaub</set>
				<set>Festival</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Hosen / Shorts (kurz)</name>
			<category>Kleidung</category>
			<sets>
				<set>Urlaub</set>
				<set>Festival</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Hosen / Jeans (lang)</name>
			<category>Kleidung</category>
			<sets>
				<set>Urlaub</set>
				<set>Festival</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Gürtel</name>
			<category>Kleidung</category>
			<sets>
				<set>Urlaub</set>
				<set>Festival</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Regenjacke</name>
			<category>Kleidung</category>
			<sets>
				<set>Urlaub</set>
				<set>Festival</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Schlafanzug</name>
			<category>Kleidung</category>
			<sets>
				<set>Urlaub</set>
				<set>Festival</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Socken</name>
			<category>Kleidung</category>
			<sets>
				<set>Urlaub</set>
				<set>Festival</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>T-Shirts</name>
			<category>Kleidung</category>
			<sets>
				<set>Urlaub</set>
				<set>Festival</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Unterwäsche</name>
			<category>Kleidung</category>
			<sets>
				<set>Urlaub</set>
				<set>Festival</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Schuhe</name>
			<category>Kleidung</category>
			<sets>
				<set>Urlaub</set>
				<set>Festival</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Wanderschuhe</name>
			<category>Kleidung</category>
			<sets>
				<set>Wandern</set>
			</sets>
		</item>
		<item>
			<name>Schneestiefel</name>
			<category>Kleidung</category>
			<sets>
				<set>Wintersport</set>
			</sets>
		</item>
		<item>
			<name>Skijacke</name>
			<category>Kleidung</category>
			<sets>
				<set>Wintersport</set>
			</sets>
		</item>
		<item>
			<name>Skihose</name>
			<category>Kleidung</category>
			<sets>
				<set>Wintersport</set>
			</sets>
		</item>
		<item>
			<name>Skisocken</name>
			<category>Kleidung</category>
			<sets>
				<set>Wintersport</set>
			</sets>
		</item>
		<item>
			<name>Handschuhe</name>
			<category>Kleidung</category>
			<sets>
				<set>Wintersport</set>
			</sets>
		</item>
		<item>
			<name>Thermowäsche</name>
			<category>Kleidung</category>
			<sets>
				<set>Wintersport</set>
			</sets>
		</item>
		<item>
			<name>Schal</name>
			<category>Kleidung</category>
			<sets>
				<set>Wintersport</set>
			</sets>
		</item>
		<item>
			<name>Hausschuhe</name>
			<category>Kleidung</category>
			<sets>
				<set>Urlaub</set>
				<set>Wintersport</set>
			</sets>
		</item>
		<item>
			<name>Adressliste für Postkarten</name>
			<category>Papiere / Unterlagen</category>
			<sets>
				<set>Urlaub</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Personalausweis / Reisepass</name>
			<category>Papiere / Unterlagen</category>
			<sets>
				<set>Urlaub</set>
				<set>Festival</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Führerschein</name>
			<category>Papiere / Unterlagen</category>
			<sets>
				<set>Urlaub</set>
				<set>Festival</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Tickets / Buchungsbelege</name>
			<category>Papiere / Unterlagen</category>
			<sets>
				<set>Urlaub</set>
				<set>Festival</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Studentenausweis / Schülerausweis</name>
			<category>Papiere / Unterlagen</category>
			<sets>
				<set>Urlaub</set>
				<set>Festival</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Handy + Ladekabel</name>
			<category>Elektronik</category>
			<sets>
				<set>Urlaub</set>
				<set>Festival</set>
				<set>Camping</set>
			</sets>
		</item>
				<item>
			<name>Tablet + Ladekabel</name>
			<category>Elektronik</category>
			<sets>
				<set>Urlaub</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Digitalkamera + Ladekabel</name>
			<category>Elektronik</category>
			<sets>
				<set>Urlaub</set>
				<set>Festival</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>eBook Reader + Ladekabel</name>
			<category>Elektronik</category>
			<sets>
				<set>Urlaub</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Taschenlampe + Batterien</name>
			<category>Elektronik</category>
			<sets>
				<set>Festival</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Kopfhörer</name>
			<category>Elektronik</category>
			<sets>
				<set>Urlaub</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Action-Camcorder</name>
			<category>Elektronik</category>
			<sets>
				<set>Wintersport</set>
			</sets>
		</item>
		<item>
			<name>Zelt + Heringe</name>
			<category>Campingzubehör</category>
			<sets>
				<set>Festival</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Isomatte</name>
			<category>Campingzubehör</category>
			<sets>
				<set>Festival</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Schlafsack</name>
			<category>Campingzubehör</category>
			<sets>
				<set>Festival</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Pavillion</name>
			<category>Campingzubehör</category>
			<sets>
				<set>Festival</set>
			</sets>
		</item>
		<item>
			<name>Campingstuhl</name>
			<category>Campingzubehör</category>
			<sets>
				<set>Festival</set>
				<set>Camping</set>
			</sets>
		</item>
		<item>
			<name>Campingtisch</name>
			<category>Campingzubehör</category>
			<sets>
				<set>Festival</set>
				<set>Camping</set>
			</sets>
		</item>
